services:
  vllm:
    image: vllm-cpu-env
    healthcheck:
      test: curl -f http://localhost:8000/v1/chat/completions || exit 1
      interval: 30s
      timeout: 10s
      retries: 10
    ports:
      - 8000:8000
    environment:
      - HUGGING_FACE_HUB_TOKEN:'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'
  python:
    image: im_ex_smolvlm
    depends_on:
      vllm:
        condition: service_healthy
    environment:
      - MY_URL:'http://localhost:8000/v1/chat/completions'
      - MY_MODEL:'HuggingfaceTB/SmolVLM-256M-Instruct '
